### PR TITLE
Update to ROM 4.0

### PR DESCRIPTION
**Pull request by alsemyonov**

### CODE REVIEW

**Review by franckverrot — CHANGES_REQUESTED** [review]
Thanks for the PR, it’s awesome.  One question though: is there a specific reason to drop JRuby?  It’s arguably pegging an old version but this could be fixed.

Thanks again!

**Comment by alsemyonov** [comment]
Oh, it was complaining on C extension in `rugged`. 

I have made another commit (on different branch) with an updated JRuby (version copied from `rom-sql`): https://travis-ci.org/alsemyonov/rom-git/jobs/341490346
But it will not pass.

**Comment by alsemyonov** [comment]
Actually that build already failed. 
Do you know JRuby version that can build C extensions? Or do you have any other questions?

**Comment by alsemyonov** [comment]
You can check that previous builds were not been able to build `rugged` too:
* https://travis-ci.org/rom-rb/rom-git/jobs/148739172 
* https://travis-ci.org/rom-rb/rom-git/jobs/148735494, 
* and even the very first one with JRuby enabled, https://travis-ci.org/rom-rb/rom-git/jobs/148735494.
 
 So I just switched off JRuby builds, since they are both useless, never-passing, and time and energy-consuming.

**Comment by solnic** [comment]
rugged doesn't support jruby, so it's OK to drop it here

**Review by franckverrot — APPROVED** [review]

**Comment by franckverrot** [comment]
I spent time looking into the rugged/JRuby issues and indeed won't spend time trying to fix this. Thanks a bunch!

PS: Just released v3.0.0

**Pull request merged**
